### ISSUE TITLE
Crash with  Tesla Essentials (cyberware.common.block.tile.PowerContainer)

### ISSUE THREAD

**Issue by Lightone** [Flaxbeard/Cyberware#30]
try connect the the energy of tesla essentials and the game crashesd

`java.lang.ClassCastException: flaxbeard.cyberware.common.block.tile.PowerContainer cannot be cast to net.darkhax.tesla.api.ITeslaConsumer
	at net.darkhax.tesla.lib.TeslaUtils.distributePowerToAllFaces(TeslaUtils.java:278)
	at com.trials.modsquad.block.TileEntities.TileSolarPanel.func_73660_a(TileSolarPanel.java:82)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)`

[Crash log](http://pastebin.com/7kBZiA3q)

**Comment by mallrat208** [comment]
This is related to #28 
In the interim you can use Cyberware 0.1.10. If you chose to do so be aware you will lose out on bug fixes that happened in 0.1.11 and 0.1.12

**Comment by Flaxbeard** [comment]
Fixed in 0.1.13
