### ISSUE TITLE
[beta-0.2.2] Conflict with Hardcore Wither?

### ISSUE THREAD

**Issue by Towsty** [Flaxbeard/Cyberware#49]
Spawning a wither with both cyberware and hardcore wither installed produces the error below.

Not sure who's end its on, I have  attached the server log and posted a report on the[ other mods tracker](https://gitlab.com/thor12022/HardcoreWither/issues/50).

[fml-server-latest.txt](https://github.com/Flaxbeard/Cyberware/files/473844/fml-server-latest.txt)

```javascript
[00:05:06] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.EntityJoinWorldEvent@1bcd1e18:
java.lang.ClassCastException: thor12022.hardcorewither.wither.WitherData cannot be cast to flaxbeard.cyberware.api.ICyberwareUserData
	at flaxbeard.cyberware.api.CyberwareAPI.getCapability(CyberwareAPI.java:365) ~[CyberwareAPI.class:?]
	at flaxbeard.cyberware.api.CyberwareAPI.isCyberwareInstalled(CyberwareAPI.java:381) ~[CyberwareAPI.class:?]
	at flaxbeard.cyberware.common.item.ItemBoneUpgrade.handleJoinWorld(ItemBoneUpgrade.java:64) ~[ItemBoneUpgrade.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_284_ItemBoneUpgrade_handleJoinWorld_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) [EventBus.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1129) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1063) [ls.class:?]
	at net.minecraft.block.BlockSkull.func_180679_a(BlockSkull.java:212) [aoy.class:?]
	at net.minecraft.item.ItemSkull.func_180614_a(ItemSkull.java:112) [aez.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:755) [ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:144) [adz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:483) [lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) [me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [jj.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [jj.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
'''

**Comment by Flaxbeard** [comment]
Strange bug - unsure how this is even possible with the way capabilities work but I'll work on it

**Comment by Towsty** [comment]
Apparently this issue was fixed on HardcoreWither's end. Have not had a chance to test yet there is an updated version released that addresses it.

**Comment by Flaxbeard** [comment]
Will close. Reopen if the issue persists.
